amend jitclass import from numba in Cellpose notebook
Hi,

I updated the numba imports for section 6.2 (3D predictions) because jitclass needs to be imported from numba.experimental otherwise we get the error message below:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-3-0fa970c2ce00> in <module>
----> 1 from numba import jitclass, float64
      2 from numba import jit

ImportError: cannot import name 'jitclass' from 'numba' (/usr/local/lib/python3.7/dist-packages/numba/__init__.py)
---------------------------------------------------------------------------

Also, the Anisotropy explanation says that the default value is 1 but by default the value was set to 2, so I set it to 1.

Thanks a lot
=)